import { Metadata } from "next"
import { Section } from "@/components/ui/section"
import { AlertTriangle } from "lucide-react"

export const metadata: Metadata = {
  title: "Disclaimer | FinVault",
  description: "Read our financial and affiliate disclaimer before using FinVault tools and resources.",
}

export default function DisclaimerPage() {
  const lastUpdated = "April 18, 2026"

  return (
    <Section className="pt-8 pb-16 lg:pt-12">
      <div className="max-w-3xl mx-auto space-y-12">
        <header className="space-y-4">
          <h1 className="heading-1 !text-4xl lg:!text-5xl">Disclaimer</h1>
          <p className="body-text text-lg">Last Updated: {lastUpdated}</p>
        </header>

        <div className="relative w-full rounded-xl border p-4 [&>svg~*]:pl-7 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground border-amber-500/50 bg-amber-500/10 text-amber-900 dark:text-amber-400">
          <AlertTriangle className="h-5 w-5 !text-amber-600 dark:!text-amber-500" />
          <h5 className="mb-1 font-bold leading-none tracking-tight">Not Financial Advice</h5>
          <div className="text-sm opacity-90 [&_p]:leading-relaxed">
            The information, calculators, and tools provided on FinVault are intended for educational and informational purposes only. They do not constitute financial, investment, legal, or tax advice.
          </div>
        </div>

        <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground prose-h2:text-foreground prose-h2:font-bold prose-h2:mt-12 prose-h2:mb-4 prose-strong:text-foreground">
          <h2>1. Educational Purposes Only</h2>
          <p>
            FinVault provides mathematical tools and articles to help you understand personal finance concepts. Any outputs generated by our calculators (including EMI, Loan, and Credit Card calculators) are estimates based on the formulas standard to the industry. However, your actual rates, figures, and obligations will vary based on your specific lending institution, credit score, fees, and market fluctuations.
          </p>
          <p>
            You should not make any major financial decisions solely based on the calculations or editorial content found on this website. <strong>We strongly recommend consulting with a certified financial planner, accountant, or legal professional</strong> before taking action on any financial matters.
          </p>

          <h2>2. Accuracy of Information</h2>
          <p>
            While we strive to keep the information on FinVault up-to-date and mathematically correct, we make no warranties or representations of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
          </p>

          <h2>3. Affiliate Disclosure</h2>
          <p>
            FinVault believes in absolute transparency. In order to keep our calculators free to use, we participate in various affiliate marketing programs. 
          </p>
          <p>
            This means that some of the links on our website (such as links recommending specific bank accounts, credit cards, or financial software) may be affiliate links. If you click on an affiliate link and make a purchase or sign up for a service, we may receive a commission at <strong>no additional cost to you</strong>. 
          </p>
          <p>
            Our editorial content and calculator logics are not influenced by advertisers or affiliate partnerships. We only recommend products or services that we believe provide value to our users.
          </p>

          <h2>4. External Links Liability</h2>
          <p>
            Through this website, you may be able to link to other websites which are not under the control of FinVault. We have no control over the nature, content, and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
          </p>

          <h2>5. Use of the Site</h2>
          <p>
            In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.
          </p>
        </div>
      </div>
    </Section>
  )
}
